
import './globals.css'
import { ClerkProvider } from "@clerk/nextjs/app-beta";
import Footer from '@/components/Footer';
import Navbar from '@/components/navbar';
import { store } from '@/app/store'
import { Provider } from 'react-redux'
import Providers from './provider';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
